# Generated by Django 4.1.7 on 2023-03-30 21:14

from django.db import migrations, models

import core.services.upload_car_service


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=core.services.upload_car_service.upload_to),
        ),
    ]
