# Generated by Django 4.2 on 2023-04-12 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carmodel_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ('id',)},
        ),
    ]
